### ISSUE TITLE
[BUG] Error occurred while enabling ServerBooster v1.1.4

### ISSUE THREAD

**Issue by WongIong** [LoneDev6/ServerBooster#72]
**Describe the bug**
As titile

**To Reproduce**
1. start the server

**Expected behavior**
Enable without error

**Screenshots**

**Info (please complete the following information):**
 - Server version: paper1.17.1
 - Client version: (example: fabric 1.15.2)
 - Plugin version: 1.1.4

**Additional context**
java.lang.NoSuchFieldError: MC1_19_R2
	at dev.lone.serverbooster.Main.onEnable(SourceFile:70) ~[ServerBooster_1.1.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LoneDev6** [comment]
update lonelibs.
