### ISSUE TITLE
[BUG] Startup Error 1.19.2 Version unsupported

### ISSUE THREAD

**Issue by UncleM0** [LoneDev6/ServerBooster#86]
**Describe the bug**
Startup Error unsopported version 1.19.2

**Info (please complete the following information):**
 - Server version:  paper 1.19.2)
 - Plugin version: 1.1.6-r4

**Additional context**
https://paste.helpch.at/iveguhugej.css

```
[20:50:53] [Server thread/INFO]: [ServerBooster] Enabling ServerBooster v1.1.6-r3
[20:50:53] [Server thread/WARN]: [ServerBooster] Invalid configuration for mob type: pig_zombie
[20:50:53] [Server thread/INFO]: Language en_us not found in folder 'lang', please download it from here: http://matteodev.it/spigot/holodrops/assets/lang.zip
[20:50:53] [Server thread/INFO]: Language en not found in folder 'lang_limiter'
[20:50:53] [Server thread/ERROR]: [ServerBooster] Error getting implementation for class dev.lone.serverbooster.entities_tracking.nms.Nms - NMS v1_19_R1
[20:50:53] [Server thread/WARN]: java.lang.ClassNotFoundException: dev.lone.serverbooster.entities_tracking.nms.impl.v1_19_R1.NMSHandler
[20:50:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177)
[20:50:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[20:50:53] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[20:50:53] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[20:50:53] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[20:50:53] [Server thread/WARN]: 	at ServerBooster_1.1.6-r4.jar//dev.lone.serverbooster.entities_tracking.nms.Nms.a(SourceFile:40)
[20:50:53] [Server thread/WARN]: 	at ServerBooster_1.1.6-r4.jar//dev.lone.serverbooster.entities_tracking.nms.Nms.a(SourceFile:15)
[20:50:53] [Server thread/WARN]: 	at ServerBooster_1.1.6-r4.jar//dev.lone.serverbooster.main.au.o(SourceFile:126)
[20:50:53] [Server thread/WARN]: 	at ServerBooster_1.1.6-r4.jar//dev.lone.serverbooster.main.au.r(SourceFile:252)
[20:50:53] [Server thread/WARN]: 	at ServerBooster_1.1.6-r4.jar//dev.lone.serverbooster.Main.onEnable(SourceFile:135)
[20:50:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:50:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[20:50:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[20:50:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[20:50:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[20:50:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[20:50:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[20:50:53] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[20:50:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[20:50:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[20:50:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[20:50:53] [Server thread/INFO]: [ServerBooster] Disabling ServerBooster v1.1.6-r3
[20:50:53] [Server thread/ERROR]: [ServerBooster] Could not find support for this Spigot version.
[20:50:53] [Server thread/ERROR]: Error occurred while enabling ServerBooster v1.1.6-r3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.lone.serverbooster.entities_tracking.nms.INms.t()" because "dev.lone.serverbooster.main.au.a" is null
	at dev.lone.serverbooster.main.au.o(SourceFile:129) ~[ServerBooster_1.1.6-r4.jar:?]
	at dev.lone.serverbooster.main.au.r(SourceFile:252) ~[ServerBooster_1.1.6-r4.jar:?]
	at dev.lone.serverbooster.Main.onEnable(SourceFile:135) ~[ServerBooster_1.1.6-r4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by LoneDev6** [comment]
Please update to 1.19.4, no reason to stay on 1.19.2 because it has bugs and performance issues.

**Comment by ii109** [comment]
I too am experiencing this same problem.
Version 1.19.2 is the most loved version.
Please solve it.
