### ISSUE TITLE
[BUG] Unsupported version 1.8.8

### ISSUE THREAD

**Issue by UncleM0** [LoneDev6/ServerBooster#87]
**Describe the bug**
Server Version Unsupported???

Server just keeps restarting

**Info (please complete the following information):**
This server is running CraftBukkit version git-iSpigot-PaperEdition (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Additional context**
https://paste.helpch.at/tanobetuba.md

```
13:22:28 WARN]: [VotingPlugin] Detected an issue with voting sites, check the plugin startup log for more details
[13:22:30 ERROR]: [ServerBooster] Error getting implementation for class dev.lone.serverbooster.entities_tracking.nms.Nms - NMS v1_8_R3
[13:22:30 WARN]: java.lang.ClassNotFoundException: dev.lone.serverbooster.entities_tracking.nms.impl.v1_8_R3.NMSHandler
[13:22:30 WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[13:22:30 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[13:22:30 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[13:22:30 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[13:22:30 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[13:22:30 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[13:22:30 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[13:22:30 WARN]:        at dev.lone.serverbooster.entities_tracking.nms.Nms.a(SourceFile:40)
[13:22:30 WARN]:        at dev.lone.serverbooster.entities_tracking.nms.Nms.a(SourceFile:15)
[13:22:30 WARN]:        at dev.lone.serverbooster.main.Y.a(SourceFile:442)
[13:22:30 WARN]:        at dev.lone.serverbooster.main.Y.b(SourceFile:448)
[13:22:30 WARN]:        at dev.lone.serverbooster.main.Y.a(SourceFile:110)
[13:22:30 WARN]:        at org.imanity.imanityspigot.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:47)
[13:22:30 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[13:22:30 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:22:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524)
[13:22:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510)
[13:22:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callItemSpawnEvent(SourceFile:325)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.World.addEntity(SourceFile:1379)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.World.addEntity(SourceFile:1348)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.Block.a(SourceFile:432)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.Block.dropNaturally(SourceFile:411)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.Block.b(SourceFile:398)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.BlockPlant.e(SourceFile:70)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.BlockPlant.b(SourceFile:52)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.Block.a(SourceFile:362)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.h(SourceFile:602)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.doTick(SourceFile:339)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1084)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:947)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:837)
[13:22:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[13:22:30 INFO]: [ServerBooster] Disabling ServerBooster v1.1.6-r3
[13:22:30 ERROR]: [ServerBooster] Could not find support for this Spigot version.
[13:22:30 ERROR]: [ServerBooster] Error getting implementation for class dev.lone.serverbooster.entities_tracking.nms.Nms - NMS v1_8_R3
[13:22:30 WARN]: java.lang.ClassNotFoundException: dev.lone.serverbooster.entities_tracking.nms.impl.v1_8_R3.NMSHandler
[13:22:30 WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[13:22:30 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[13:22:30 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[13:22:30 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[13:22:30 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[13:22:30 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[13:22:30 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[13:22:30 WARN]:        at dev.lone.serverbooster.entities_tracking.nms.Nms.a(SourceFile:40)
[13:22:30 WARN]:        at dev.lone.serverbooster.entities_tracking.nms.Nms.a(SourceFile:15)
[13:22:30 WARN]:        at dev.lone.serverbooster.main.Y.a(SourceFile:499)
[13:22:30 WARN]:        at dev.lone.serverbooster.main.Y.a(SourceFile:442)
[13:22:30 WARN]:        at dev.lone.serverbooster.main.Y.b(SourceFile:448)
[13:22:30 WARN]:        at dev.lone.serverbooster.main.Y.a(SourceFile:110)
[13:22:30 WARN]:        at org.imanity.imanityspigot.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:47)
[13:22:30 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[13:22:30 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:22:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524)
[13:22:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510)
[13:22:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callItemSpawnEvent(SourceFile:325)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.World.addEntity(SourceFile:1379)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.World.addEntity(SourceFile:1348)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.Block.a(SourceFile:432)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.Block.dropNaturally(SourceFile:411)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.Block.b(SourceFile:398)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.BlockPlant.e(SourceFile:70)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.BlockPlant.b(SourceFile:52)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.Block.a(SourceFile:362)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.h(SourceFile:602)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.doTick(SourceFile:339)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1084)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:947)
[13:22:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:837)
[13:22:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[13:22:30 ERROR]: [ServerBooster] Could not find support for this Spigot version.
[13:22:30 ERROR]: Could not pass event ItemSpawnEvent to ServerBooster v1.1.6-r3
java.lang.NullPointerException: Cannot invoke "dev.lone.serverbooster.entities_tracking.nms.INms.b(org.bukkit.Material)" because the return value of "dev.lone.serverbooster.entities_tracking.nms.Nms.a()" is null
        at dev.lone.serverbooster.main.Y.a(SourceFile:499) ~[?:?]
        at dev.lone.serverbooster.main.Y.a(SourceFile:442) ~[?:?]
        at dev.lone.serverbooster.main.Y.b(SourceFile:448) ~[?:?]
        at dev.lone.serverbooster.main.Y.a(SourceFile:110) ~[?:?]
        at org.imanity.imanityspigot.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:47) ~[spigot.jar:git-iSpigot-PaperEdition]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callItemSpawnEvent(SourceFile:325) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.World.addEntity(SourceFile:1379) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.World.addEntity(SourceFile:1348) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.Block.a(SourceFile:432) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.Block.dropNaturally(SourceFile:411) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.Block.b(SourceFile:398) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.BlockPlant.e(SourceFile:70) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.BlockPlant.b(SourceFile:52) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.Block.a(SourceFile:362) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.WorldServer.h(SourceFile:602) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(SourceFile:339) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1084) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:947) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:837) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[13:22:30 INFO]: Stopping server
```

**Comment by LoneDev6** [comment]
Hello,
your report will be looked into as soon as possible.
Please do not bump this thread and don't post it on multiple platforms.

Thanks a lot for your patience.
