### ISSUE TITLE
I CANT STOP SERVER

### ISSUE THREAD

**Issue by alberto1111111** [LoneDev6/ServerBooster#94]
WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world surv_the_end: EntityComplexPart['Ender Dragon'/108, uuid='ccee94de-1492-4cfe-9a73-8ee2a64d4cd7', l='ServerLevel[surv_the_end]', x=54.92, y=67.13, z=34.74, cx=0, cz=0, tl=0, v=false, d=false]
[22:10:36 WARN]:        at net.minecraft.server.v1_16_R3.PlayerChunkMap.addEntity(:2104)
[22:10:36 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
[22:10:36 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:10:36 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22:10:36 WARN]:        at dev.lone.serverbooster.entities_tracking.nms.impl.v1_16_R3.tasks.EntitiesOptimizerProcess.a(SourceFile:227)
[22:10:36 WARN]:        at dev.lone.serverbooster.entities_tracking.nms.impl.v1_16_R3.NMSHandler.a(SourceFile:80)
[22:10:36 WARN]:        at dev.lone.serverbooster.main.y.a(SourceFile:107)
[22:10:36 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(:40)
[22:10:36 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(:76)

**Comment by LoneDev6** [comment]
Please post the full server log
